pathfindertools/ipfs-camp-2022

devent.toml
This is a test PR to remove a few extra spaces
=> Removed extra space

devent.toml
Location, website & RSVP Link updated
=> Location, website & RSVP Link updated

devent.toml
The file has been updated to include FAQ content as per the copy on Notion: https://www.notion.so/Website-Copy-39f7e4c206a449678ba84989064a70f1
=> FAQ Section content updated

devent.toml
Adds `:` instead of line breaks
=> Update FAQ formatting

devent.toml
- Update Organizer name
- Removes "all scheduled events are optional"
=> Small content/text tweaks

devent.toml
Updated all track names and and descriptions from "website tagline" field, including those proposed: https://docs.google.com/spreadsheets/d/1Y5GNkP13p1F23ObhOoCRUwfPaZjxmvb8WwQainCmkos/edit#gid=0
=> Track names & Descriptions update

events/browsers.toml, events/compute-over-data.toml, events/content-routing.toml, events/data-transfer.toml, events/decentralized-job-fair.toml, events/gaming-metaverse-and-video.toml, events/growing-with-ipfs.toml, events/ipfs-201.toml, events/ipfs-apps-for-fun-and-awesome.toml, events/ipfs-for-creatives.toml, events/ipfs-implementations.toml, events/ipfs-operators-and-enterprise.toml, events/keynotes.toml, events/learning-ipfs-101.toml, events/libp2p-day.toml, events/libp2p-privacy.toml, events/measurement-and-performance.toml
Various tweaks to the .toml file details in `events` folder, based on latest communication with Track Leaders
=> Update track details

devent.toml, website/components/header.js, website/components/tickets.js
- Add ticket links to 5 types
- Change Tickets button to link to tickets section (rather than General lu.ma only)
- Change navigation "About IPFS" to "About"
- A few other text tweaks (punctuation, meals, etc.)
=> Ticket links & content tweaks

events/ipfs-201.toml, website/components/event.js
This PR does two things:
- Update the 201 schedule
- Improve styling of the track modal
- make schedule table padding smaller on mobile so there's more space for the talk description
- make the model taller - making it easier to view the modal on mobile
- add markdown support for talk descriptions
- Add zebra striping to the table so that larger descriptions are clearly associated with a talk title.
https://bafybeiaz2tr5zys32uzmzxmcaebgnhzqdhugh4bot3dmzwcd6cqt22frg4.on.fleek.co/#IPFS-201-App-Design-Patterns-and-Developer-Tools
=> Styling improvements & updates to the 201 track

events/libp2p-privacy.toml
cc: @willscott for a quick review before merging.
=> libp2p privacy session agenda

events/ipfs-project-fair.toml
=> Rename Science Fair to Project Fair

website/components/event.js
- Remove "Organization" (currently all blank).
- Remove parentheses around (Attendees).
=> update popup formatting

events/content-routing.toml
a bit of shifts to make sure everyone can make their commitments and filling in remaining space
=> Fill out additional details for content routing track

events/compute-over-data.toml
Schedule updated to better match the room availability!
=> Update CoD track to new more compressed schedule

events/measurement-unconf.toml
The second part of the Measurements track will be in Unconf mode. This PR adds the somewhat tentative items that the group will focus on.
=> Measurements Unconf Description & Agenda

devent.toml
- Update with venue name
- Remove sponsorship line
=> Make venue obvious

events/data-transfer.toml
=> Fix typo in Jorropo

events/measurement-unconf.toml
Swapping two talks within the Unconf part of the Measurements and Performance track.
=> Talks slot swap - measurements and performance track

events/data-transfer.toml
This is the mostly final track schedule. Still getting 👍 on talk descriptions from some of the speakers but I think the agenda is mostly set.
=> Clean up data transfer track

events/browsers.toml
* move day to 29th
* only half day track now
=> Browsers and Platforms track update

events/ipfs-operators-and-enterprise.toml
Mario gave me an updated talk description and title
=> update mario talk and title

events/ipfs-201.toml
=> update geoip talk description

events/ipfs-implementations.toml
cc @b5 – my thinking is to do ~15 talk and then Q&A but lmk if the format will not allow for questions, then we can shorten to 15-20min
=> add  description to the spec talk

events/ipfs-implementations.toml
=> chore: fix typo

devent.toml
Did this with some Python:
``` python
import toml
t = toml.load('./devent.toml')
speakers = t['speakers']
speakers.sort(key=lambda x: x['name'].split()[-1])
print(toml.dumps({'speakers': speakers}))
```
(and tweaked the TOML so the parser doesn't barf)
=> Re-sort speakers

events/ipfs-opening-party.toml
- Add opening party
Beware that this adds it to the list of tracks too:
=> add opening party

devent.toml
- change affiliation of 1 speaker
- move last 2 speakers into alphabetical order
=> update affiliation, sort by alpha

README.md, events/_ipfs-camp-track-template.toml, events/data-transfer.toml, events/gaming-metaverse-and-video.toml, events/ipfs-101-and-user-apps.toml, events/ipfs-201.toml, events/measurement-unconf.toml
This allowed for creating a sheet like https://docs.google.com/spreadsheets/d/1O9wNhnhr13q7HVIe_wAB_F_9YR9A-F_9/edit?usp=sharing&ouid=117939455223568021966&rtpof=true&sd=true so can navigate the schedule for each day.
=> Cleanup readme and .toml files so can get CSV dump

events/measurement-and-performance.toml
=> Update Measurement And Performance Track

events/content-routing.toml
added to end of content routing track
cc @jbenet
=> add juan and david fireside
